[package]
name = "rpt"
version = "0.1.0"
authors = ["Eric Zhang <ekzhang1@gmail.com>"]
edition = "2018"

[dependencies]
color-eyre = "0.5.6"
glm = { version = "0.8.0", package = "nalgebra-glm" }
image = "0.23.10"
rand = "0.7.3"
rand_distr = "0.3.0"
rayon = "1.5.0"

[profile.dev]
opt-level = 2
lto = "thin"

[profile.release]
codegen-units = 1
lto = "fat"
